### ISSUE TITLE
Full size Image Download And Albums

### ISSUE THREAD

**Issue by ZeroNilZero** [ClayF/instagram-image-downloader#1]
This Script was the best i ever seen on the web.
Just little questions:
1. does it download the full size image? like what we do by adding "/media?size=l" at the end of photo link?
2. how about instagram albums? more than one photo in a photo links?

**Comment by NexProME** [comment]
And Also sometimes it return bad quality images.

**Comment by NexProME** [comment]
By changing `$imageURL` to `$imageURL = 'https://www.instagram.com/p/'.$data['code'].'/media/?size=l';` and enabling redirect on curl, got what i want but in some case got 404, 302 errors.
And also because some user changed usernames its better to make dir base on user_id not username to avoid re-downloading in future.

**Comment by NexProME** [comment]
By changing `$imageURL` to `$imageURL = 'https://www.instagram.com/p/'.$data['code'].'/media/?size=l';` and enabling redirect on curl, got what i want but in some case got 404, 302 errors.
And also because some user changed usernames its better to make dir base on user_id not username to avoid re-downloading in future.

**Comment by PixellUp** [comment]
@NexProME Can you please create PR.
